### ISSUE TITLE
BUG: Checking indexing status

### ISSUE THREAD

**Issue by adorosario** [adorosario/apify-customgpt#1]
I think the way we are checking to see that all the uploaded documents have been indexed is wrong. Here is the way to do it correctly: 
https://github.com/adorosario/wordpress-to-customgpt/blob/main/app.py#L101

# ISSUES
1. It does not correctly check ALL the paginated sets. 

# PROPOSED CODE
1. Sleeps for 5 seconds the moment it finds an un-indexed document. 
2. Only moves to the next paginated list after the previous ones have been all indexed. 

# TEST OF SUCCESS
1. Confirm that the number of documents uploaded is correctly corresponds to the indexing status you see printed.

**Comment by Abdallahyx** [comment]
FIXED
